version: '3.8'

services:
  spotify-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=false
      - PORT=5000
      # GitHub Developer Pack API Keys (set these in .env file)
      - BRIGHT_DATA_PROXY_URL=${BRIGHT_DATA_PROXY_URL}
      - BRIGHT_DATA_USERNAME=${BRIGHT_DATA_USERNAME}
      - BRIGHT_DATA_PASSWORD=${BRIGHT_DATA_PASSWORD}
      - FINGERPRINTJS_API_KEY=${FINGERPRINTJS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - bot_data:/app/data
      - /dev/shm:/dev/shm  # For Chrome shared memory
    shm_size: 2gb
    cap_add:
      - SYS_ADMIN  # Required for Chrome sandbox
    security_opt:
      - seccomp:unconfined  # Required for Chrome
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for session persistence (for scaling)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    # Uncomment to expose Redis
    # ports:
    #   - "6379:6379"

volumes:
  bot_data:
  redis_data:
